[package]
name = "srs_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
noir_rs = { git = "https://github.com/zkpassport/noir_rs.git", branch = "v0.36.0", package = "noir_rs" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"